# All necessary workflows from the part 1.

name: QuoteAPI CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the Github repository
      uses: actions/checkout@v5
    - name: Configuring Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24'
    - name: Installing dependencies
      run: npm ci  
    - name: Linting
      run: npm run lint
    - name: Running tests
      run: npm test
