# All necessary workflows from the part 2.

name: QuoteAPI CD

on:
  workflow_run:
    workflows: ["QuoteAPI CI"]
    types:
    - completed

jobs:
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Deploying
      env:
        deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK }}
      run: |
        if [ -z "$RENDER_DEPLOY_HOOK"]; then
          echo "RENDER_DEPLOY_HOOK secret is not set."
          exit 1
        fi

        curl "$deploy_url"